### ISSUE TITLE
[BUG] RoadRunner integration create traces with TraceId 0, rejected by APM agent

### ISSUE THREAD

**Issue by adrien-f** [DataDog/dd-trace-php#1860]
### Bug description

While trying out the new RoadRunner integration, the generated traces are rejected by the APM agent with the following error message: 

```
023-01-16 14:31:33 UTC | TRACE | DEBUG | (run.go:248 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero): service:"roadrunner" name:"web.request" resource:"GET /api/monitoring/status/liveness" spanID:4833514502463363744 start:1673879492413635000 duration:3026000 meta:<key:"_dd.p.dm" value:"-1" > meta:<key:"http.method" value:"GET" > meta:<key:"http.status_code" value:"200" > meta:<key:"http.url" value:"http://127.0.0.1:8000/api/monitoring/status/liveness" > meta:<key:"http.useragent" value:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" > meta:<key:"span.kind" value:"server" > metrics:<key:"_dd.rule_psr" value:1 > metrics:<key:"_sampling_priority_v1" value:1 > metrics:<key:"php.compilation.total_time_ms" value:149.706 > metrics:<key:"process_id" value:13272 > type:"web"
```

I've narrowed it down to here: https://github.com/DataDog/dd-trace-php/blob/master/ext/ddtrace.c#L1867 where `DDTRACE_G(distributed_trace_id)` is `NULL`

Reproduction case with

```
docker-compose run --rm 8.0-buster bash
```

and tweaking to start an agent in the compose environment.

```
cat << EOF > .rr.yaml
server:
  command: "php -dlog_errors='on' -ddatadog.trace.client_ip_header_disabled='true' -derror_log='/tmp/dd-trace-php/tests/Frameworks/Roadrunner/Version_2/dd_php_error.log' -dddtrace.request_init_hook='/tmp/dd-trace-php/bridge/dd_wrap_autoloader.php' -dxdebug.remote_enable='1' -dxdebug.remote_host='host.docker.internal' -dxdebug.remote_autostart='1' /tmp/dd-trace-php/tests/Frameworks/Roadrunner/Version_2/worker.php"
  env: {"DD_TRACE_AGENT_PORT":8126,"DD_AGENT_HOST":"agent","DD_TRACE_AGENT_FLUSH_AFTER_N_REQUESTS":1,"DD_TRACE_AGENT_FLUSH_INTERVAL":333,"DD_TEST_INTEGRATION":"true","DD_AUTOLOAD_NO_COMPILE":"true","DD_TRACE_DEBUG":"false","DD_TRACE_HEADER_TAGS":"x-header","DD_TRACE_CLI_ENABLED":1}
  exec_timeout: 5s
http:
  address: 0.0.0.0:9999
  pool:
    num_workers: 1
    destroy_timeout: 1s
logs:
  output: /tmp/dd-trace-php/tests/Frameworks/Roadrunner/Version_2/roadrunner_error.log
  err_output: /tmp/dd-trace-php/tests/Frameworks/Roadrunner/Version_2/roadrunner_error.log
EOF
```

Then if you `curl http://127.0.0.1:9999`, we see in the agent logs:

```
2023-01-16 15:59:03 UTC | TRACE | DEBUG | (run.go:248 in Debugf) | Dropping invalid trace: TraceID is zero (reason:trace_id_zero): service:"roadrunner" name:"web.request" resource:"GET /" spanID:2830416086992939982 start:1673884742821847352 duration:211734 meta:<key:"_dd.p.dm" value:"-1" > meta:<key:"http.method" value:"GET" > meta:<key:"http.status_code" value:"200" > meta:<key:"http.url" value:"http://127.0.0.1:9999/" > meta:<key:"http.useragent" value:"curl/7.64.0" > meta:<key:"span.kind" value:"server" > metrics:<key:"_dd.rule_psr" value:1 > metrics:<key:"_sampling_priority_v1" value:1 > metrics:<key:"php.compilation.total_time_ms" value:52.085 > metrics:<key:"process_id" value:12206 > type:"web"
```

### PHP version

```
PHP 8.0.17 (cli) (built: Jan  4 2023 15:54:10) ( NTS DEBUG )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies
    with ddtrace v1.0.0-nightly, Copyright Datadog, by Datadog
```

### Tracer version

dd-trace-php `afe28a4da3b3ad66b2e00bb6b48dd4d5571e4077`

### Installed extensions

<details>
<summary>[PHP Modules]</summary>

```
[PHP Modules]
apcu
ast
Core
ctype
curl
date
ddtrace
dom
FFI
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mcrypt
memcached
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
ddtrace
```
</details>

### OS info

From the Docker:

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```

#### Output of phpinfo() (ddtrace >= 0.47.0)

Straight from the Docker image mentioned in `CONTRIBUTING.md`

Let me know if you need more information.

Internal Support Ticket: 1066454
