### ISSUE TITLE
Unable to activate Trace Search & Analytics

### ISSUE THREAD

**Issue by funkjedi** [DataDog/dd-trace-php#460]
Hitting a wall trying to get Trace Search & Analytics activated. Tried every permutation of configurations I've been able to find to no avail.

Appreciate any ideas anyone might have.

--

**Environment vars injected via nginx**
```
fastcgi_param DD_TRACE_ENABLED true;
fastcgi_param DD_TRACE_ANALYTICS_ENABLED true;
fastcgi_param DD_LARAVEL_ANALYTICS_ENABLED true;
fastcgi_param DD_LARAVEL_ANALYTICS_SAMPLE_RATE 1.0;
fastcgi_param DD_APM_ANALYZED_SPANS "laravel|laravel.request=1";
```

**Agent config**
```
apm_config:
  enabled: true
  analyzed_spans:
    laravel|laravel.request: 1
```
