### ISSUE TITLE
TraceId not being injected in the logs

### ISSUE THREAD

**Issue by sdepablos** [DataDog/dd-trace-php#681]
As per explained in [Connect Logs and Traces](https://docs.datadoghq.com/tracing/advanced/connect_logs_and_traces/?tab=php) we've added a a Monolog processor to our logs so they receive the trace and span id, but so far we've had no luck. 

What we've found is that while the trace id is generated correctly at any point of our code - we just did a `echo GlobalTracer::get()->getActiveSpan()->getTraceId();` at it worked - once we arrive to the Monolog processor the `GlobalTracer::get()->getActiveSpan();` returns _null_ for the same request.

We're using agent v6.15.1 wit the PHP agent 0.35.0, in a Symfony 3.4 project, with the following config:
```yml
monolog:
  handlers:
    datadog:
      type: stream
      path: "%kernel.logs_dir%/datadog-%kernel.environment%.log"
      level: info
      formatter: monolog.formatter.json
services:
  datadog_processor:
    class: App\Core\Infrastructure\Monolog\DatadogProcessor
    tags:
      - { name: monolog.processor, handler: datadog }
```
```php
namespace App\Core\Infrastructure\Monolog;

use DDTrace\GlobalTracer;

class DatadogProcessor
{
    public function __invoke(array $record)
    {
        $span = GlobalTracer::get()->getActiveSpan();
        if (null === $span) {
            return $record;
        }
        $record['message'] .= sprintf(
            ' [dd.trace_id=%d dd.span_id=%d]',
            $span->getTraceId(),
            $span->getSpanId()
        );

        return $record;
    }
}
```
