### ISSUE TITLE
K8s dont like env vars with colons

### ISSUE THREAD

**Issue by justinsoong** [DataDog/dd-trace-php#736]
Simply want to do this`DD_TRACE_GLOBAL_TAGS=env:production`, unfortunately k8s doesn't like colons in the environment variables.

Any one have workarounds for this, can we consider other seperator values?

**Comment by labbati** [comment]
Hi @justinsoong thank you for opening the issue. Actually I was quite surprised to learn that but it seems confirmed even in k8s issues [here](https://github.com/kubernetes/kubernetes/issues/53201) and the PR that seems to be the candidate to add this feature is still [open](https://github.com/kubernetes/kubernetes/pull/83032).

Let me sync with experts of k8s here and will get back to you soon.

**Comment by labbati** [comment]
Hi @justinsoong I got from good news from @cgilmour (thanks).

If you do something like this, it should work:

```
    spec:
      containers:
      - env:
        .....
        - name: DD_TRACE_GLOBAL_TAGS
          value: env:production
```

If that is not working for you, might you please share a broader snippet of code that you are using so we can better help?
